### ISSUE TITLE
Native hack description

### ISSUE THREAD

**Issue by ZorGleH** [jacomyal/domino.js#22]
In a hack method, instead of writing something like

``` javascript
this.log('[HACK] Do something');
```

, I suggest a native "description" key

``` javascript
description: 'Do something'
```

which would do the same.

"`description`" could even be a function with event as param

``` javascript
triggers: ['doCoffee', 'doTea'],
description: function(e) {
  return 'I am going to the kitchen to ' + e.type + ' for the breakfast';
}
```

**Comment by jacomyal** [comment]
I do like this idea of a `description` attribute to specify what each hack does. I could even be used to generate documentation or ask help from the JavaScript console. Especially since I usually add a log at the beginning of each hack I write.

But I think making it a function is not a good idea:
- First, the great idea with this `description` attribute is that it could be consulted even when the hack is not actually executed. Then, your example would not work.
- Also, if I can write a function for the description, I would probably prefer to write my log directly inside the main hack function - and especially if both functions have the same signature.

I'll integrate this `description` attribute in the next release. Thanks for the idea!

**Comment by straux** [comment]
I suggest to add the "description" attribute to properties, hacks, and
services, as it would be a simple way to provide help and documentation for
an whole application.

2013/5/20 Alexis Jacomy notifications@github.com

**Comment by ZorGleH** [comment]
You're right about the function.
By the way, why not extending this idea to properties, services, etc. That would be DOUBLE SUN POWER!

**Comment by ZorGleH** [comment]
Argh, you were faster than me straux!

**Comment by jacomyal** [comment]
Hell yeah, I love the idea. And a `help` function that returns the description of indicated element!

**Comment by jacomyal** [comment]
Just implemented for the hacks. You still can add descriptions in properties etc... but it will be kinda useless. I don't exactly know yet how you would like to use a `domInst.help()` method. Any idea?

**Comment by ZorGleH** [comment]
Nice! As discussed with straux, `domInst.help()` could log a minimal description of the instance, with only IDs and descriptions, and `domInst.help('full')` could log the full instance Object. It would be particularly helpful when working on a minified code.
It could also be used to generate a static documentation in text or html or whatever format when you build the project, but I don't know if it's really useful...

**Comment by jacomyal** [comment]
Yep, sounds good to me - except the static file generation. This works well for properties, services and shortcuts - but how to identify hacks in help?

**Comment by ZorGleH** [comment]
There are 2 options in my opinion:
- give hacks a mandatory id (but I don't like it because it's heavy and used only for help purpose)
- identify them by triggers (ok it's not unique but does it matter?)

**Comment by jacomyal** [comment]
I think I am going to do it like that:
- You can specify a unique ID for hacks
- If not specified, I will try to take `hack.triggers.join('/') + '->' + hack.dispatch.join('/')`
- If `dispatch` is not specified, I will use an incremental ID based on triggers (`myEvent1`, `myEvent2`, etc...)

No time to implement this today, it will come in the next release. I open a new ticket for this feature.

**Comment by ZorGleH** [comment]
Agreed!
